site_name: MKDocs Tutorial for Architecture
theme: 
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: green
      accent: blue
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
copyright: Copyright &copy; 2023 <a href="https://github.com/frankehle/Sample-MKDocs" target="_blank" rel="noopener">Frank Who's Yo Daddy Ehle</a>
#display a link to the repository; will be rendered next to the search bar on big screens
repo_url: https://github.com/frankehle/Sample-MKDocs